[project]
name = 'contracts-temp'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.book-registry]
path = 'contracts/book-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.entitlement]
path = 'contracts/entitlement.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
